### PR TITLE
Generate timestamp on archive for org

### PR DESCRIPTION
**Pull request by StephenOTT**
Generates a timestamp: `%Y%m%dT%H%M%S` = 20160109T152503 for each
archive of the organization.  Every time a archive is actioned it will
generate a new folder inside of the organization folder with the
timestamp.

### CODE REVIEW

**Comment by StephenOTT** [comment]
@benbalter take a look at proposed changes that use optionparse that allows the user to manage timestamp versioning of Repo, Wiki, and Issues.

**Comment by benbalter** [comment]
@StephenOTT Take a look at `master`, as I refactored things a bit (but this change shouldn't be too hard to rebase, AFAIK). 

I'm still not sold on the idea of versioning Git repositories with timestamps. I understand "this is how government agencies create snapshots of other artifacts not already in version control", but if we've already go the best version control system, why make our own?

**Comment by StephenOTT** [comment]
I agree with your reasonings for not wanting to version the Git repos.
The only "Gov perspective"/enterprise perspective that can be provided is: There is a chance that the Git Repo history is modified/removed/deleted.  
If that occurred, there would be no record of when it occurred, because the backup would only contain the last pull of the Repo.
For a Risk Management perspective, Server Space is cheap, and backing up the full repo/issues/etc as part of a versioned backup is the most secure/and least risky option, and eliminates any possibility of not having the record of the changed Git Repo.
I totally agree that Git has the history and why do it again, and one "could" secure the branches from deletion.  But that is not something the staff doing the backups would likely be able to control or monitor on an on-going basis, and would add to the complexity of the Business Management/Internal Rules that staff need to follow in any sort of Gov or enterprise.

By not versioning, a un-needed risk is created.  The risk of the Git history being changed.  It's a small risk, but it is still a risk, and can be mitigated through timestamps.  

From a Gov/any enterprise perspective, the cost of storing duplicate Repos as the backups is extremely minor.  Especially when they do rolling backups.
:smile: 
So all that to say worst case, if versioning is not added, someone can just do the versioning when they run their script/command to run the backup.  They can generate the timestamp at a higher level such as: [timestamp] > orgName > Repo, Issues, Wiki, etc. rather than what this PR proposed of: OrgName > [timestamp] > Repo, issues, wiki, etc.

Making it a option using the OptionParse like i submitted above would be the best of both worlds, no?  By default it would not version control, but someone can turn that on versioning using parameters.

**Comment by StephenOTT** [comment]
@benbalter Hey, one thing that just came to mind and not sure of the answer myself, but how would you account for someone modifying repo history such as documented by GitHub: https://help.github.com/articles/remove-sensitive-data/

If there are no versions of the repo, then it is possible to lose history, whether accidentally or through malicious intent.

Whats your thoughts @benbalter ?

**Pull request closed without merging**
